### ISSUE TITLE
Si on est que 2 à créer la structure - David et Sabine : c'est un souci ?

### ISSUE THREAD

**Issue by sabinesafi** [lien-de-consentement/exploration#10]
On est OK pour 2 raisons :
- Pas mal de personnes se sont déclarées intéressées par nous rejoindre, donc on devrait pas rester seul.e.s trop longtemps,
- Au pire on reste tous les 2 un moment, et ça nous fait déjà un véhicule administratif qui nous convient pour nos activités respectives.

**Comment by DavidBruant** [comment]
A priori c'est bon, réouvrir si c'est un problème
