### ISSUE TITLE
Comment ça marche avec l'argent ?

### ISSUE THREAD

**Issue by DavidBruant** [lien-de-consentement/exploration#2]
https://hackmd.io/aQrxFCvjSjOlNy97PB2Cvg

**Comment by sabinesafi** [comment]
Comment ça marche avec l’argent ?
Toutes les réponses sont à prendre avec une poignée de sel

Julia :

Est-ce que je peux me garantir d’avoir 1000€/mois que je travaille ou ne travaille pas ?
Salaire fixe (genre SMIC) tous les mois
Rémunération indépendante de la quantité de temps travaillé dans le mois

David :

oui, sous réserve d’avoir l’argent en trésorerie

Sabine :
La loi impose aux CAE une compta analytique ‘pour chaque activité autonome’ : une personne un compte à priori.
Mais la loi ne semble pas interdire qu’un compte de résultat individuel soit négatif…

Comment on fait pour avoir l’argent en trésorerie ?

avoir soi-même fait rentré avant suffisamment d’argent avant
que d’autres aient fait rentré suffisamment d’argent avant et le “partage” ?
Combien faut faire rentrer dans la structure pour se payer 1000€/mois ?

D’après https://mon-entreprise.fr/sécurité-sociale/salarié
pour 1185€ net/mois (~SMIC), l’entreprise dépense 1659 €

Il y a des charges communes ?

Oui

Comptable (Bilan comptable, TVA, Impôts sur les Sociétés, Déclaration auprès des impôts)
Volet social (fiche de paye et virements)
Impôts fixes : Cotisation Foncière des Entreprises
Révision coopérative ?
Combien ça coûte ?
Comment on le paye ? (comment on répartit ce coût entre nous ?)

Certaines CAE font payer 7-11% du chiffre d’affaire à chaque entrepreneur-salarié

Si on commence la CAE, au début je vais facturer via la CAE, mais sans être payée
Comment on démarre le truc ?

Par exemple, rentrer l’équivalent de 3 (?) mois de salaires avant de commencer à se payer
C’est faisable légalement via un contrat CAPE

yaf dit : En fait, on peut se payer dès le deuxième mois (si on a facturé sur le premier)

Il existe des subventions spécifiques aux CAE

Est-ce que Pôle Emploi présever les allocations chômages pendant un contrat CAPE ? (je crois que oui)

Oui, si le montant du contrat ne passe pas l’allocations. En général, on joue sur des petit contrat au début (quelques heures aux smic), compensé par l’allocation chomage.

Est-ce qu’on peut avoir la CAE et un autre employeur ?

A priori oui (si CAE n’est pas un plein-temps) ?
