### ISSUE TITLE
On lit la loi qui créé les CAE

### ISSUE THREAD

**Issue by DavidBruant** [lien-de-consentement/exploration#3]
https://hackmd.io/1bGjkJckT_iD29NQkVR16A?edit

**Comment by sabinesafi** [comment]
# Croyances, envies et ce que la loi permet

## Textes de référence

### CAE

- LOI n° 2014-856 du 31 juillet 2014 relative à l'économie sociale et solidaire : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000029313296&categorieLien=id
- Loi n° 47-1775 du 10 septembre 1947 portant statut de la coopération (version 2019) : https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000684004

### Statut d'Entrepreneur-Salarié-Associé

- Partie législative (?) : https://legi.now.sh/code/LEGITEXT000006072050/section/LEGISCTA000029317511
- Partie réglementaire (?) : https://legi.now.sh/code/LEGITEXT000006072050/section/LEGISCTA000031395635


## Croyances

- Le statut d'Entrepreneur-Salarié-Associé permet à la fois d'être salarié et de respecter le consentement
- Il y a une coutume chez les CAE qui est d'avoir une "équipe support". Il s'agit d'une coutume et non d'une obligation légale
- la compta analytique doit permettre à chaque entrepreneur-salarié de voir l'état de ses comptes (vis à vis de sont activité et de ses rémunérations) « La coopérative met à la disposition de l'entrepreneur salarié associé un état des comptes faisant apparaître le détail des charges et des produits liés à son activité. » Art. L. 7332-3 https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=C780E7627779BA4D0AF52863438D9ADD.tplgfr44s_1?idArticle=JORFARTI000029313929&cidTexte=JORFTEXT000029313296&dateTexte=29990101&categorieLien=id
- « « Art. L. 7332-6.-Le conseil de prud'hommes est seul compétent pour connaître des litiges relatifs au contrat mentionné au 2° de l'article L. 7331-2. » « Toute clause attributive de juridiction incluse dans un contrat conclu entre un entrepreneur salarié associé et une coopérative d'activité et d'emploi dont il est l'associé est nulle.  » https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=C780E7627779BA4D0AF52863438D9ADD.tplgfr44s_1?idArticle=JORFARTI000029313929&cidTexte=JORFTEXT000029313296&dateTexte=29990101&categorieLien=id L'article 7331-2 fait référence à « 1° Crée et développe une activité économique en bénéficiant d'un accompagnement individualisé et de services mutualisés mis en œuvre par la coopérative en vue d'en devenir associé ; » sans précision effective sur les modalité de l'accompagnement individualisé. Mais est-ce que c'est les prud'hommes seuls qui sont compétent pour jugé si oui ou non il y a eu accompagnement ?
- Une CAE est une coopération "augmentée" ou une SCOP "augmentée"
- On est obligé de passer par l'URSCOP pour créer une SCOP
    => (Stéphane) : nan, on peut créer une SCOP sans l'URSCOP
- En tant qu'entrepreneur-salarié-associé, une personne peut choisir librement son salaire mois par mois (selon ce que la personne a facturé par exemple)
- C'est pas facile de varier le salaire, mais c'est facile de faire varier le temps de travail déclaré
- dans une CAE, il reste une personne physique à désigner qui serait le référente et responsable légale
- la gérance/responsabilité d'une CAE diffère d'une autre coopérative



## Envies

- Respect du consentement
    - Pas de lien de subordination entre individus
- accompagner et aider des personnes qui n'arrive pas forcement à entrer dans le millieu de la programmation
- Structure avec le minimum de contrainte possible
    - L'URSCOP, ça a l'air d'être une contrainte


## Glossaire

- coopérative
    - 
- société
- SCOP
    - Sociétés COopératives de Production (il existe d'autres déroulement de l'acronyme moins "légaux"/"officiels"/récents), avant c'était Sociétés Coopératives Ouvrières de Production.
- URSCOP
    - Union Régionale des SCOP


## Questions 

> Les coopératives d'activité et d'emploi sont des sociétés coopératives de production, des sociétés coopératives d'intérêt collectif ou des coopératives de toute autre forme dont les associés sont notamment entrepreneurs salariés.
Une CAE est-elle forcément une SCOP ?

> Compta analytique, bilan actif-passif individuel : arrivera-t-on à faire nous-mêmes? Jusqu'où peut-on se passer d'un comptable ?


## Notes, extraits

### Titre III ter : La coopérative d'activité et d'emploi
Article 26-41
Modifié par LOI n° 2016-1088 du 8 août 2016 - art. 70 

*Les coopératives d'activité et d'emploi ont pour objet principal l'appui à la création et au développement d'activités économiques par des entrepreneurs personnes physiques.*

*Ces coopératives mettent en œuvre un accompagnement individualisé des personnes physiques et des services mutualisés.*

Les coopératives d'activité et d'emploi sont des sociétés coopératives de production, des sociétés coopératives d'intérêt collectif ou des coopératives de toute autre forme dont les associés sont notamment entrepreneurs salariés. Elles sont régies par la présente loi, par le livre III de la septième partie du code du travail, ainsi que par les dispositions des lois particulières applicables à certaines catégories de société coopérative.

Les statuts de la coopérative déterminent les moyens mis en commun par elle à cet effet et les modalités de rémunération des personnes mentionnées au premier alinéa du présent article, dans des conditions prévues par décret en Conseil d'Etat.

Les articles 25-1 à 25-5 sont applicables aux sociétés coopératives d'activité et d'emploi.

**Parmi les 25-1 à 25-5 : **

> Les sociétés coopératives et leurs unions dont l'activité dépasse une certaine importance, appréciée à partir de seuils fixés par décret en Conseil d'Etat, se soumettent tous les cinq ans à un contrôle, dit “ révision coopérative ” [...]
> La révision est effectuée par un réviseur agréé.


### Article L7331-2
Créé par LOI n°2014-856 du 31 juillet 2014 - art. 48
Est entrepreneur salarié d'une coopérative d'activité et d'emploi toute personne physique qui : 

1° Crée et développe une activité économique en bénéficiant d'un accompagnement individualisé et de services mutualisés mis en œuvre par la coopérative en vue d'en devenir associé ; 

2° Conclut avec la coopérative un contrat, établi par écrit, comportant : 

a) Les objectifs à atteindre et les obligations d'activité minimale de l'entrepreneur salarié ; 
b) Les moyens mis en œuvre par la coopérative pour soutenir et contrôler son activité économique ; 
c) Les modalités de calcul de la contribution de l'entrepreneur salarié au financement des services mutualisés mis en œuvre par la coopérative, dans les conditions prévues par les statuts de celle-ci ; 
d) Le montant de la part fixe et les modalités de calcul de la part variable de la rémunération de l'entrepreneur salarié, en application de l'article L. 7332-3 ; 
e) La mention des statuts en vigueur de la coopérative ; 
f) Les conditions dans lesquelles sont garantis à l'entrepreneur salarié ses droits sur la clientèle qu'il a apportée, créée et développée, ainsi que ses droits de propriété intellectuelle.


### Article L7332-2
Créé par LOI n°2014-856 du 31 juillet 2014 - art. 48
La coopérative d'activité et d'emploi est **responsable de l'application, au profit des entrepreneurs salariés associés**, des dispositions du livre Ier de la troisième partie relatives à la durée du travail, aux repos et aux congés, ainsi que de celles de la quatrième partie relatives à la santé et à la sécurité au travail **lorsque les conditions de travail, de santé et de sécurité au travail ont été fixées par elle ou soumises à son accord**. 

Dans tous les cas, les entrepreneurs salariés associés bénéficient des avantages légaux accordés aux salariés, notamment en matière de congés payés. 

### Article R7331-1
La coopérative d'activité et d'emploi assure l'ensemble des obligations légales, réglementaires et contractuelles inhérentes à l'exercice de l'activité économique de chaque entrepreneur salarié avec lequel elle conclut le contrat d'entrepreneur salarié mentionné au 2° de l'article L. 7331-2. 

Elle assure notamment les obligations fiscales, sociales et comptables relatives à l'activité de l'entrepreneur salarié.

### Article R7331-2
La coopérative d'activité et d'emploi assure un accompagnement individuel de chaque entrepreneur salarié en vue de favoriser le développement de son activité économique.

Les statuts de la coopérative d'activité et d'emploi déterminent les services mutualisés proposés pour l'accompagnement individuel et collectif des entrepreneurs salariés.

L'assemblée générale délibère chaque année sur les actions nécessaires à l'accompagnement individuel et collectif des entrepreneurs salariés et les ressources à affecter à cet effet.

### Article R7331-3
Le contrat d'entrepreneur salarié mentionné au 2° de l'article L. 7331-2 définit les conditions dans lesquelles l'entrepreneur salarié bénéficie, par période de douze mois, d'au moins deux entretiens individuels d'accompagnement faisant l'objet d'un document écrit et signé par l'entrepreneur salarié. Ce document comporte notamment le bilan et les perspectives d'évolution prévisible de son activité économique, les actions individuelles et collectives nécessaires au développement de son activité économique ainsi que les besoins d'accompagnement.

### Article R7331-5
La coopérative d'activité et d'emploi tient, pour chaque activité économique autonome :

1° Un compte analytique de bilan qui récapitule les éléments de l'actif et du passif ;

2° Un compte analytique de résultat qui récapitule les produits et les charges de l'exercice.

L'entrepreneur salarié a accès au système d'information de la coopérative pour consulter le compte d'activité et les opérations comptables qui le concernent, ainsi que pour prendre connaissance de sa situation financière. A défaut de système d'information, ces informations lui sont transmises une fois par mois par la coopérative ou à sa demande pour les besoins de gestion de son activité.

### Article R7331-11
La rémunération prévue à l'article L. 7332-3, fixée au contrat, est composée : 

1° D'une part fixe versée mensuellement dont le montant est déterminé forfaitairement en fonction des objectifs d'activités minimales définis dans le contrat de l'entrepreneur salarié ; 

2° D'une part variable calculée pour chaque exercice en fonction du chiffre d'affaires défini à l'article L. 7332-3. Un acompte sur la part variable de la rémunération peut être versé mensuellement.


### Article R7331-12
En fin d'exercice, la coopérative d'activité et d'emploi procède à la régularisation du calcul de la part variable de la rémunération de chaque entrepreneur salarié et au versement du solde restant dû dans un délai maximum d'un mois après la date de l'assemblée générale statuant sur la clôture des comptes de l'exercice.

[...]
