### ISSUE TITLE
Comment on rentre ?

### ISSUE THREAD

**Issue by sabinesafi** [lien-de-consentement/exploration#5]
https://hackmd.io/Z0Vy9avrRiOIhpY00u2AXA

**Comment by DavidBruant** [comment]
# Comment on rentre ?

- garder le respect des valeurs (consentement) tout en haut
- être inclusif.ve.s envers celles et ceux qui ont moins facilement accès à créer ce genre de structures
- se sentir en sécurité (vis-à-vis de ses vulnérabilités, l'administratif-financier, etc.)

**Solution temporaire proposée : rencontrer les potentiels entrant.e.s pour se faire une idée de si on est à l'aise, si on les sent sur le respect de nos valeurs. En gardant en tête le point d'attention sur la non-homogénéité du groupe.**
 
Est-ce que l'argent est une contrainte à l'entrée ?
- apport au capital ? On pourrait mettre 1€ chacun.e au capital.
- avoir une activité économique déjà soutenable ?



# Le point sur les CAE telles qu'elles existent ailleurs...

Une CAE "classique" a pour vocation d'accompagner le lancement de l'activité des entrepreneurs salariés...
> Est-ce que c'est une exigence de la loi ?

## Critères à l'entrée
Est-ce que ton activité est couverte par l'assurance de la CAE ? ex : si tu as besoin de locaux, si tu bosses dans le bâtiment...
Est-ce qu'on met des restrictions à l'entrée sur le type d'activité ? éthique etc.

## Des règles de fonctionnement
Quelles règles pour devenir associé ?
Un.e référent.e pour suivre chaque membre tous les mois, faire le point sur ce qu'on peut se payer, etc. ?

**--> On n'est pas totalement clair.e.s sur ce qui relève de la loi et ce qui relève de l'usage des CAE existantes... Et si on allait lire la loi de 2014 sur le sujet ?**

**Comment by sabinesafi** [comment]
Nouvelle position : 

On dit non à tout le monde par défaut

On ne nous demande pas, c'est nous qui proposerons

On bossera ou vivra sûrement des trucs avec la personne sans que la personne n'entre dans la structure. Et si ça se passe bien, la discussion viendra
