### ISSUE TITLE
Chercher de l'info sur comment on crée une CAE

### ISSUE THREAD

**Issue by sabinesafi** [lien-de-consentement/exploration#8]
- [x] chercher sur google "comment créer une cae"
- [ ] chercher un cabinet de compta qui a l'habitude des CAE
- [ ] appeler l'URSCOP et leur demander
- [ ] contacter des CAE existantes et leur demander comment ils ont fait (Coop'Alpha, Co-Actions, celle de la pote de Sabine, celles que connaît Yannick ?)
- [ ] regarder sur les "formulaires" (?) de création de boîte s'il y a une option CAE
- [ ] demander sur Twitter

**Comment by DavidBruant** [comment]
Indirectement, les statuts de Codeurs en Libertés donnent des infos : https://gitlab.com/CodeursEnLiberte/fondations/blob/master/statuts.md

**Comment by DavidBruant** [comment]
- [ ] Appeler le Greffe du Tribunal de Commerce
- [ ] Appeler la BPI

**Comment by DavidBruant** [comment]
A priori, on fait pas une CAE, on fait une SCOP et on a trouvé comment faire : créer une société commerciale et dans les statuts, pour la forme, indiqué que c'est une SCOP et faire référence à la loi de 78
