### ISSUE TITLE
Avoir une discussion sur les moyens que la CAE met en place

### ISSUE THREAD

**Issue by sabinesafi** [lien-de-consentement/exploration#9]
https://hackmd.io/x0zdKFq7QSe6Fevyq_Dxeg

**Comment by DavidBruant** [comment]
# Les moyens que la CAE met en place

Echo à https://github.com/lien-de-consentement/exploration/issues/4

- Accompagnement individualisé pour le développement de l'activité économique : pas l'choix 😅
    - Disponibilité de personnes pour organiser/animer des entretiens/discussions/ateliers/formations
    - Conseil juridique
    - Soutien psychologique/émotionnel
    - ...
- Au cas par cas, possibilité de créer un/des pots communs pour assurer des salaires fixes et le montant minimum pour les indemnités de fin de contrat
- Outil numérique/process/service (comptable) pour faire la compta analytique individuelle
- Souscription à des assurances et complémentaire santé pertinentes
